# -*- coding: utf-8 -*-
"""feature_engineering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZGy1NRnOWRxaHFFHQcMyTY2KThOX0tEV
"""

def create_features(users, interactions, content):
    # دمج العنوان + الوصف + الوسوم
    content['corpus'] = content['title'] + " " + content['description'] + " " + content['tags']

    # إنشاء user_profiles
    user_profiles = interactions.groupby('user_id')['content_id'].apply(list).reset_index()
    user_profiles = user_profiles.merge(users[['user_id','interest','age','level']], on='user_id', how='left')
    user_profiles.to_csv("user_profiles.csv", index=False)

    return content, user_profiles

