# -*- coding: utf-8 -*-
"""hybrid_recommender

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1on1KVh0hnoGh44UhLfoJUapc77DdKiUR
"""

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def hybrid_recommend(user_id, content_id, user_profiles, content, tfidf_matrix, top_n=5):
    user_data = user_profiles[user_profiles['user_id']==user_id].iloc[0]
    age = user_data['age']
    user_content_ids = user_data['content_id']

    if age < 13:
        recommended = content.iloc[content_id-1:content_id-1+top_n][['title','level','duration']]
    else:
        indices = [i-1 for i in user_content_ids]
        user_vectors = tfidf_matrix[indices]
        user_profile_vector = np.asarray(user_vectors.mean(axis=0))
        similarity_scores = cosine_similarity(user_profile_vector, tfidf_matrix).flatten()
        top_indices = similarity_scores.argsort()[-top_n:][::-1]
        recommended = content.iloc[top_indices][['title','level','duration']]

    return recommended

