# -*- coding: utf-8 -*-
"""preprocess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJM0Q5mfFnuGkvWlhEZr6hzUtx4lm377
"""

import pandas as pd

def load_raw_data():
    users = pd.read_csv('users.csv')
    content = pd.read_csv('content.csv')
    interactions = pd.read_csv('interactions.csv')
    return users, content, interactions


def preprocess_users(users):
    users['interest'] = users['interest'].fillna("General")
    users['age'] = users['age'].fillna(users['age'].median()).astype(int)
    users['level'] = users['level'].fillna("Beginner")
    users = users[(users['age'] >= 3) & (users['age'] <= 20)]
    return users


def preprocess_content(content):
    content['title'] = content['title'].fillna("Untitled")
    content['description'] = content['description'].fillna("")
    content['tags'] = content['tags'].fillna("General")
    content['level'] = content['level'].fillna("Beginner")

    content['duration'] = content['duration'].fillna(content['duration'].median())
    content = content[(content['duration'] > 0) & (content['duration'] <= 120)]

    return content


def preprocess_interactions(interactions):
    interactions['timestamp'] = pd.to_datetime(interactions['timestamp'], errors='coerce')
    interactions['timestamp'] = interactions['timestamp'].fillna(pd.Timestamp.now())

    if 'time_spent' in interactions.columns:
        interactions['time_spent_minutes'] = interactions['time_spent'] / 60
        interactions.drop('time_spent', axis=1, inplace=True)

    interactions = interactions[interactions['time_spent_minutes'] >= 0]
    return interactions


def preprocess_all():
    users, content, interactions = load_raw_data()
    users = preprocess_users(users)
    content = preprocess_content(content)
    interactions = preprocess_interactions(interactions)
    return users, content, interactions

