# -*- coding: utf-8 -*-
"""tfidf_recommender

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0xYQz4gKZjxrp93s2IkpJsLmvG6UIZ9
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def build_tfidf(content):
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(content['corpus'])
    return vectorizer, tfidf_matrix

def recommend_tfidf(content_id, content, tfidf_matrix, top_n=5):
    sim_scores = cosine_similarity(tfidf_matrix[content_id-1], tfidf_matrix).flatten()
    top_indices = sim_scores.argsort()[-top_n:][::-1]
    return content.iloc[top_indices][['title', 'level', 'duration']]

