# -*- coding: utf-8 -*-
"""user_profile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/153Ga2iH7eWFUHdGyvbAw_UbEqwwYqlA4
"""

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def recommend_user_profile(user_id, user_profiles, content, tfidf_matrix, top_n=5):
    user_content_ids = user_profiles[user_profiles['user_id']==user_id]['content_id'].values[0]
    indices = [i-1 for i in user_content_ids]
    user_vectors = tfidf_matrix[indices]
    user_profile_vector = np.asarray(user_vectors.mean(axis=0))
    similarity_scores = cosine_similarity(user_profile_vector, tfidf_matrix).flatten()
    top_indices = similarity_scores.argsort()[-top_n:][::-1]
    return content.iloc[top_indices][['title','level','duration']]

