# -*- coding: utf-8 -*-
"""rule_based

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_CDua1jTfLcOhdywCLHngCCaY868NzG
"""

from tfidf_recommender import recommend_tfidf

def rule_based_recommend(age, content_id, content, tfidf_matrix, top_n=5):
    if age < 13:
        return content.iloc[content_id-1:content_id-1+top_n][['title','level','duration']]
    else:
        return recommend_tfidf(content_id, content, tfidf_matrix, top_n)

